#ifndef STEGOSTATUS_H
#define STEGOSTATUS_H
enum class StegoStatus {
    SUCCESS,
    IMAGE_NOT_FOUND,
    FILE_NOT_FOUND,
    FILE_TOO_LARGE,
    OUT_OF_ROOM,
    INVALID_HEADER,
    DATA_NOT_ENCRYPTED,
    FILE_OPEN_FAILED,
    VIDEO_OPEN_FAILED,
    DECRYPTION_FAILED,
    INVALID_MEDIA,
    VIDEO_REENCODING_FAILED
};

#endif // STEGOSTATUS_H
